from agentuity import AgentRequest, AgentResponse, AgentContext
import json
import random
import string

async def run(request: AgentRequest, response: AgentResponse, context: AgentContext):
    # Get the query as plain text
    query = await request.data.text()

    # Create a storage key from the query
    storage_key = query.lower().replace(' ', '_')

    context.logger.info(f"Checking storage storage_key={storage_key}")

    # Try to get from storage first
    stored = await context.kv.get("demo-storage", storage_key)

    if stored.exists:
        # Found in storage - return stored data
        stored_result = await stored.data.text()
        context.logger.info(f"Found in storage! storage_key={storage_key}")

        return response.json({
            "source": "storage",
            "query": query,
            "result": stored_result,
            "message": "Retrieved from storage"
        })

    # Not found in storage - generate result
    context.logger.info(f"Not found in storage - generating result storage_key={storage_key}")

    code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=5))
    result = f"Result {code} generated by {context.agent.name}"

    # Store in KV storage with 5 minute TTL (300 seconds)
    await context.kv.set("demo-storage", storage_key, result, {"ttl": 300})

    context.logger.info(f"Result stored storage_key={storage_key} ttl=300s")

    return response.json({
        "source": "generated",
        "query": query,
        "result": result,
        "message": "Generated and stored for 5 minutes - send the same message again to retrieve from storage!"
    })

def welcome():
    return {
        'welcome': 'Learn KV storage - send the same message twice to see it retrieved from storage.',
        'prompts': [
            {'data': 'hello', 'contentType': 'text/plain'}
        ]
    }
