import type { AgentRequest, AgentResponse, AgentContext } from "@agentuity/sdk";

export default async function Agent(
  request: AgentRequest,
  response: AgentResponse,
  context: AgentContext
) {
  // Get the query as plain text
  const query = await request.data.text();

  // Create a storage key from the query
  const storageKey = query.toLowerCase().replace(/\s+/g, '_');

  context.logger.info('Checking storage', { storageKey });

  // Try to get from storage first
  const stored = await context.kv.get('demo-storage', storageKey);

  if (stored.exists) {
    // Found in storage - return stored data
    const storedResult = await stored.data.text();
    context.logger.info('Found in storage!', { storageKey });

    return response.json({
      source: 'storage',
      query,
      result: storedResult,
      message: 'Retrieved from storage'
    });
  }

  // Not found in storage - generate result
  context.logger.info('Not found in storage - generating result', { storageKey });

  const code = Math.random().toString(36).substring(2, 7).toUpperCase();
  const result = `Result ${code} generated by ${context.agent.name}`;

  // Store in KV storage with 5 minute TTL (300 seconds)
  await context.kv.set('demo-storage', storageKey, result, { ttl: 300 });

  context.logger.info('Result stored', {
    storageKey,
    ttl: '300s (5 minutes)'
  });

  return response.json({
    source: 'generated',
    result,
    message: 'Generated and stored for 5 minutes - send the same message again to retrieve from storage!'
  });
}

export const welcome = () => ({
  welcome: 'Learn KV storage - send the same message twice to see it retrieved from storage.',
  prompts: [
    { data: 'hello', contentType: 'text/plain' }
  ]
});
