name: Sync Docs to Vector Store (PR & Push)

on:
  push:
  pull_request:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed and removed files (last 2 commits)
        id: files
        run: |
          last2=$(git rev-list --max-count=2 HEAD)
          commit_arr=($last2)
          if [ "${#commit_arr[@]}" -eq 2 ]; then
            base_commit=${commit_arr[1]}
            head_commit=${commit_arr[0]}
          else
            base_commit=${commit_arr[0]}
            head_commit=${commit_arr[0]}
          fi
          echo "Comparing $base_commit..$head_commit"
          echo "changed=$(git diff --name-only $base_commit $head_commit -- 'content/**/*.mdx' | xargs)" >> $GITHUB_OUTPUT
          echo "removed=$(git diff --name-only --diff-filter=D $base_commit $head_commit -- 'content/**/*.mdx' | xargs)" >> $GITHUB_OUTPUT

      - name: Trigger Agentuity Sync Agent
        run: |
          changed_json=$(jq -n --arg files "${{ steps.files.outputs.changed }}" '$files | split(" ") | map(select(length > 0))')
          removed_json=$(jq -n --arg files "${{ steps.files.outputs.removed }}" '$files | split(" ") | map(select(length > 0))')
          curl https://agentuity.ai/webhook/f61d5ce9d6ed85695cc992c55ccdc2a6 \
            -X POST \
            -H "Content-Type: application/json" \
            -d '{"changedFiles":'$changed_json', "removedFiles":'$removed_json'}' 